### ISSUE TITLE
Harbor CLI Issues

### ISSUE THREAD

**Issue by jmakanjuola** [int32bit/python-harborclient#17]
All thoughts and suggestions are welcome.

##Issue 1: Harbor CLI

Harbor command:

```
harbor user-create --username test --password Testing1 --email test@test.com --realname test
 CommandError: Unable to authorize user 'admin': {"reason": "Not Allowed", "message": "<html>
 <head><title>405 Not Allowed</title></head>
 <body bgcolor="white">
 <center><h1>405 Not Allowed</h1></center>
 <hr><center>nginx/1.13.10</center>
 </body>
 </html>
 "}
```

```
harbor  --debug --insecure project-list
DEBUG (connectionpool:813) Starting new HTTPS connection (1): local:443
DEBUG (connectionpool:393) https://local:443 "POST /login HTTP/1.1" 405 174
CommandError: Unable to authorize user 'admin': {"reason": "Not Allowed", "message": "<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.13.10</center>
</body>
</html>
"}
```

## Issue 2: Native Curl Command/Outputs

````
curl -X GET "https://local/api/users/current" -H "accept: application/json"

Output: { Blank}
```

```
curl -X GET "https://local/api/projects?name=test&owner=admin&page=1" -H "accept: application/json"

Outputs:  { null }
```

**Comment by stephenwolfe1** [comment]
Had the same issue running harbor with an nginx ingress. Fixed by updating https://github.com/int32bit/python-harborclient/blob/master/harborclient/client.py#L268 to `self.baseurl + "c//login",`

Also needed to find 'beegosessionID' and replace with 'sid' running on harbor 1.7.5. At some point the cookie name for the session id has changed.

**Comment by mandar14** [comment]
@jmakanjuola  facing same issue for info initial info command to?? , How did you login using admin?

**Comment by xinity** [comment]
been testing harborcli on the latest version of harbor, still not working sadly :( 
I've tried what @stephenwolfe1 suggested without the 'c' , but still not working.
I'm still having the : 
```
CommandError: Unable to authorize user 'admin': {"reason": "Method Not Allowed", "message": "<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.15.11</center>
</body>
</html>
"}
Time: 0h:00m:03s  
```

This client could be really useful if we could find a way to fix it properly

**Comment by int32bit** [comment]
@stephenwolfe1  Could you upload your PR to fix this ? Thanks

**Comment by meyerbro** [comment]
This fixed my issue, REMEMBER to add "/" in the end of your goharbor URL, while defining your alias... This can help you @xinity...

**Comment by xinity** [comment]
@meyerbro i may have missed this tips :) 
let me try it soon as I'm working on a harbor implementation project :)

**Comment by liudonggang** [comment]
Harbor command:
harbor  --debug  --os-baseurl xxx.xxx.xxx.xxx --os-username admin --os-password xxxxxx --os-project 1 list
### 
**DEBUG (connectionpool:205) Starting new HTTP connection (1): 10.18.101.85:80
DEBUG (connectionpool:393) http://10.18.101.85:80 "POST /c/login HTTP/1.1" 404 513**
CommandError: Unable to authorize user 'admin': {"reason": "Not Found", "message": "<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title>404 - Page Not Found</title>
<style>

*{
	maring: 0;
	padding: 0;
}

a:link{
	color: #1f3759;
	text-decoration: none;
}
a:active{
	color: #1f3759;
	text-decoration: none;
}
a:hover{
	color: #9fb7d9;
	text-decoration: none;
}
a:visited{
	color: #1f3759;
	text-decoration: none;
}

a.underline, .underline{
	text-decoration: underline;
}

#content{
	margin: 0 auto;
	width: 800px;
}

#main-body{
	text-align: center;
}

.status-code {
    font-weight: bolder;
    font-size: 4em;
    vertical-align: middle;
}

.status-text {
    font-weight: bold;
    font-size: 3em;
    margin-left: 10px;
    vertical-align: middle;
}

.status-subtitle {
    font-size: 18px;
}

</style>
</head>
<body>
    <div id="content">             
        <div id="main-body">
			<div>
		        <span class="status-code">404</span>
		        <span class="status-text">Page Not Found</span>
		    </div>
		    <div class="status-subtitle">
		        <p> <a href="/harbor" class="underline">Home</p>
		    </div>
        </div>
    </div>
</body>
</html>
"}
### 
**Why this error?，this page is https://xxx.xxx.xxx.xxx/static/setting.json page,How can we solve this problem？？**

**Comment by riccardomanfrin** [comment]
I'm having the same issue. Harbor core is 1.7.1
Advices?

**Comment by riccardomanfrin** [comment]
> I'm having the same issue. Harbor core is 1.7.1
> Advices?

Ok.. actually the issue is with pulling. do as the README.md says: clone and build
